const API_BASE = 'https://vaddfiksldaebnzaccks.supabase.co/functions/v1';
const REPORT_ENDPOINT = `${API_BASE}/report`;
const DELETE_ENDPOINT = `${API_BASE}/report-delete`;
const SAVE_ENDPOINT = `${API_BASE}/report-save`;

const i18n = {
  en: {
    meetingReport: 'Meeting Report',
    generatedBy: 'Generated by MeetMind AI',
    downloadPdf: 'Download PDF',
    shareReport: 'Share Report',
    editReport: 'Edit Report',
    saveChanges: 'Save Changes',
    cancelEdit: 'Cancel',
    loadingTitle: 'Loading report…',
    loadingText: 'MeetMind AI is preparing your meeting report.',
    saveErrorTitle: 'Couldn’t save changes',
    deleteErrorTitle: 'Couldn’t delete report',
    errorTryAgain: 'Please try again.',
    close: 'Close',
    deleteReport: 'Delete Report',
    executiveSummary: 'Executive Summary',
    keyMetrics: 'Key Metrics',
    architecture: 'Architecture & Process',
    insights: 'Insights',
    decisions: 'Decisions',
    tasks: 'Tasks',
    owners: 'Owners',
    risks: 'Risks',
    detailedReport: 'Detailed report',
    transcript: 'Meeting Transcript',
    showTranscript: 'Show Full Meeting Transcript',
    hideTranscript: 'Hide Meeting Transcript',
    duration: 'Duration',
    participants: 'Participants',
    actionItems: 'Tasks',
    decisionCount: 'Decisions',
    riskCount: 'Risks',
    task: 'Task',
    owner: 'Owner',
    dueDate: 'Due Date',
    notSpecified: 'Not specified',
    copied: 'Report link copied.',
    deleted: 'This report has been deleted',
    deletedDescription: 'The owner deleted this report, so its contents are no longer available.',
    deletedProductTitle: 'Turn your meeting into a ready-to-use executive report',
    deletedProductText: 'MeetMind AI turns a meeting into a clear summary, decisions, tasks, owners, risks and key metrics.',
    deletedPreviewLabel: 'Example of a MeetMind executive report',
    deletedCta: 'Create a report in MeetMind AI',
    deletedCtaHint: 'Upload a meeting recording and get a structured result automatically.',
    notFound: 'Report not found or no longer available.',
    missingToken: 'Report token is missing.',
    deleteTitle: 'Delete this report?',
    deleteText: 'The report will no longer be available through this link.',
    deleteConfirm: 'Delete report',
    cancel: 'Cancel',
    deleteDone: 'Report deleted.',
    deleteFailed: 'Could not delete report. Please try again later.',
    saveFailed: 'Could not save report. Please try again.',
    footerGenerated: 'Generated by MeetMind AI',
    footerTagline: 'Transform conversations into clarity.',
    footerCta: 'Create your own meeting report:'
  },
  ru: {
    meetingReport: 'Отчёт по встрече',
    generatedBy: 'Создано MeetMind AI',
    downloadPdf: 'Скачать PDF',
    shareReport: 'Поделиться',
    editReport: 'Редактировать',
    saveChanges: 'Сохранить',
    cancelEdit: 'Отменить',
    loadingTitle: 'Загружаем отчёт…',
    loadingText: 'MeetMind AI готовит отчёт по вашей встрече.',
    saveErrorTitle: 'Не удалось сохранить изменения',
    deleteErrorTitle: 'Не удалось удалить отчёт',
    errorTryAgain: 'Попробуйте ещё раз.',
    close: 'Закрыть',
    deleteReport: 'Удалить отчёт',
    executiveSummary: 'Резюме встречи',
    keyMetrics: 'Ключевые метрики',
    architecture: 'Архитектура и процесс',
    insights: 'Инсайты',
    decisions: 'Решения',
    tasks: 'Задачи',
    owners: 'Владельцы',
    risks: 'Риски',
    detailedReport: 'Детальный отчёт',
    transcript: 'Расшифровка встречи',
    showTranscript: 'Показать полную расшифровку встречи',
    hideTranscript: 'Скрыть расшифровку встречи',
    duration: 'Длительность',
    participants: 'Участники',
    actionItems: 'Задачи',
    decisionCount: 'Решения',
    riskCount: 'Риски',
    task: 'Задача',
    owner: 'Ответственный',
    dueDate: 'Срок',
    notSpecified: 'Не указано',
    copied: 'Ссылка на отчёт скопирована.',
    deleted: 'Этот отчёт был удалён',
    deletedDescription: 'Владелец удалил этот отчёт, поэтому его содержимое больше недоступно.',
    deletedProductTitle: 'Превратите встречу в готовый executive-отчёт',
    deletedProductText: 'MeetMind AI превращает встречу в понятное резюме, решения, задачи, ответственных, риски и ключевые метрики.',
    deletedPreviewLabel: 'Пример executive-отчёта MeetMind',
    deletedCta: 'Создать отчёт в MeetMind AI',
    deletedCtaHint: 'Загрузите запись встречи — структурированный результат будет подготовлен автоматически.',
    notFound: 'Отчёт не найден или больше недоступен.',
    missingToken: 'Не передан токен отчёта.',
    deleteTitle: 'Удалить этот отчёт?',
    deleteText: 'Отчёт больше не будет доступен по этой ссылке.',
    deleteConfirm: 'Удалить отчёт',
    cancel: 'Отменить',
    deleteDone: 'Отчёт удалён.',
    deleteFailed: 'Не удалось удалить отчёт. Попробуйте позже.',
    saveFailed: 'Не удалось сохранить отчёт. Попробуйте ещё раз.',
    footerGenerated: 'Создано MeetMind AI',
    footerTagline: 'Превращаем разговоры в ясность действий.',
    footerCta: 'Создайте свой отчёт:'
  },
  es: {
    meetingReport: 'Informe de reunión',
    generatedBy: 'Generado por MeetMind AI',
    downloadPdf: 'Descargar PDF',
    shareReport: 'Compartir informe',
    editReport: 'Editar informe',
    saveChanges: 'Guardar cambios',
    cancelEdit: 'Cancelar',
    loadingTitle: 'Cargando informe…',
    loadingText: 'MeetMind AI está preparando el informe de tu reunión.',
    saveErrorTitle: 'No se pudieron guardar los cambios',
    deleteErrorTitle: 'No se pudo eliminar el informe',
    errorTryAgain: 'Inténtalo de nuevo.',
    close: 'Cerrar',
    deleteReport: 'Eliminar informe',
    executiveSummary: 'Resumen ejecutivo',
    keyMetrics: 'Métricas clave',
    architecture: 'Arquitectura y proceso',
    insights: 'Hallazgos',
    decisions: 'Decisiones',
    tasks: 'Tareas',
    owners: 'Responsables',
    risks: 'Riesgos',
    detailedReport: 'Informe detallado',
    transcript: 'Transcripción de la reunión',
    showTranscript: 'Mostrar transcripción completa',
    hideTranscript: 'Ocultar transcripción',
    duration: 'Duración',
    participants: 'Participantes',
    actionItems: 'Tareas',
    decisionCount: 'Decisiones',
    riskCount: 'Riesgos',
    task: 'Tarea',
    owner: 'Responsable',
    dueDate: 'Fecha límite',
    notSpecified: 'No especificado',
    copied: 'Enlace del informe copiado.',
    deleted: 'Este informe ha sido eliminado',
    deletedDescription: 'El propietario eliminó este informe, por lo que su contenido ya no está disponible.',
    deletedProductTitle: 'Convierte tu reunión en un informe ejecutivo listo para usar',
    deletedProductText: 'MeetMind AI transforma una reunión en un resumen claro, decisiones, tareas, responsables, riesgos y métricas clave.',
    deletedPreviewLabel: 'Ejemplo de informe ejecutivo de MeetMind',
    deletedCta: 'Crear un informe en MeetMind AI',
    deletedCtaHint: 'Sube la grabación de una reunión y recibe automáticamente un resultado estructurado.',
    notFound: 'Informe no encontrado o ya no disponible.',
    missingToken: 'Falta el token del informe.',
    deleteTitle: '¿Eliminar este informe?',
    deleteText: 'El informe dejará de estar disponible mediante este enlace.',
    deleteConfirm: 'Eliminar informe',
    cancel: 'Cancelar',
    deleteDone: 'Informe eliminado.',
    deleteFailed: 'No se pudo eliminar el informe. Inténtalo de nuevo más tarde.',
    saveFailed: 'No se pudo guardar el informe. Inténtalo de nuevo.',
    footerGenerated: 'Generado por MeetMind AI',
    footerTagline: 'Transformamos conversaciones en claridad.',
    footerCta: 'Crea tu propio informe:'
  },
  pt: {
    meetingReport: 'Relatório da reunião',
    generatedBy: 'Gerado pelo MeetMind AI',
    downloadPdf: 'Baixar PDF',
    shareReport: 'Compartilhar relatório',
    editReport: 'Editar relatório',
    saveChanges: 'Salvar alterações',
    cancelEdit: 'Cancelar',
    loadingTitle: 'Carregando relatório…',
    loadingText: 'O MeetMind AI está preparando o relatório da sua reunião.',
    saveErrorTitle: 'Não foi possível salvar as alterações',
    deleteErrorTitle: 'Não foi possível excluir o relatório',
    errorTryAgain: 'Tente novamente.',
    close: 'Fechar',
    deleteReport: 'Excluir relatório',
    executiveSummary: 'Resumo executivo',
    keyMetrics: 'Métricas principais',
    architecture: 'Arquitetura e processo',
    insights: 'Insights',
    decisions: 'Decisões',
    tasks: 'Tarefas',
    owners: 'Responsáveis',
    risks: 'Riscos',
    detailedReport: 'Relatório detalhado',
    transcript: 'Transcrição da reunião',
    showTranscript: 'Mostrar transcrição completa',
    hideTranscript: 'Ocultar transcrição',
    duration: 'Duração',
    participants: 'Participantes',
    actionItems: 'Tarefas',
    decisionCount: 'Decisões',
    riskCount: 'Riscos',
    task: 'Tarefa',
    owner: 'Responsável',
    dueDate: 'Prazo',
    notSpecified: 'Não especificado',
    copied: 'Link do relatório copiado.',
    deleted: 'Este relatório foi excluído',
    deletedDescription: 'O proprietário excluiu este relatório, por isso o conteúdo não está mais disponível.',
    deletedProductTitle: 'Transforme sua reunião em um relatório executivo pronto para usar',
    deletedProductText: 'O MeetMind AI transforma uma reunião em resumo, decisões, tarefas, responsáveis, riscos e métricas principais.',
    deletedPreviewLabel: 'Exemplo de relatório executivo do MeetMind',
    deletedCta: 'Criar um relatório no MeetMind AI',
    deletedCtaHint: 'Envie a gravação de uma reunião e receba automaticamente um resultado estruturado.',
    notFound: 'Relatório não encontrado ou indisponível.',
    missingToken: 'O token do relatório está ausente.',
    deleteTitle: 'Excluir este relatório?',
    deleteText: 'O relatório deixará de estar disponível por este link.',
    deleteConfirm: 'Excluir relatório',
    cancel: 'Cancelar',
    deleteDone: 'Relatório excluído.',
    deleteFailed: 'Não foi possível excluir o relatório. Tente novamente mais tarde.',
    saveFailed: 'Não foi possível salvar o relatório. Tente novamente.',
    footerGenerated: 'Gerado pelo MeetMind AI',
    footerTagline: 'Transformamos conversas em clareza.',
    footerCta: 'Crie seu próprio relatório:'
  }
};

let currentMeeting = null;
let currentLang = 'en';
let currentToken = null;
let isEditMode = false;

const $ = (id) => document.getElementById(id);

function t(key) {
  return (i18n[currentLang] && i18n[currentLang][key]) || i18n.en[key] || key;
}


function detectInitialLanguage() {
  const params = new URLSearchParams(window.location.search);
  const requested = String(params.get('lang') || '').toLowerCase();
  if (['en', 'ru', 'es', 'pt'].includes(requested)) return requested;

  const browserLang = String(navigator.language || navigator.userLanguage || 'en').toLowerCase();
  if (browserLang.startsWith('ru')) return 'ru';
  if (browserLang.startsWith('es')) return 'es';
  if (browserLang.startsWith('pt')) return 'pt';
  return 'en';
}

function setLoadingLabels() {
  document.documentElement.lang = currentLang;
  const title = $('loadingTitle');
  const text = $('loadingText');
  if (title) title.textContent = t('loadingTitle');
  if (text) text.textContent = t('loadingText');
}

function showFeedbackModal(title, message) {
  const modal = $('feedbackModal');
  if (!modal) return;
  $('feedbackModalTitle').textContent = title;
  $('feedbackModalText').textContent = message;
  $('feedbackModalClose').textContent = t('close');
  modal.classList.remove('hidden');
}

function hideFeedbackModal() {
  const modal = $('feedbackModal');
  if (modal) modal.classList.add('hidden');
}

function escapeHtml(value) {
  return String(value ?? '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;');
}

function isEmptyValue(value) {
  if (value == null) return true;
  if (Array.isArray(value)) return value.length === 0;
  if (typeof value === 'object') return Object.keys(value).length === 0;
  const normalized = String(value).replace(/[#*•\-\s.]/g, '').trim().toLowerCase();
  return !normalized || ['неуказано', 'not specified', 'n/a', 'none', 'null'].includes(normalized);
}
function cleanText(value) {
    return String(value ?? '').trim();
}

function normalizeReport(report = {}) {
  return {
       headline: report.headline || '',

    title: report.title || report.meeting_title || '',
    subtitle: report.subtitle || report.meeting_subtitle || '',
    objective: report.objective || report.meeting_objective || '',
    meeting_type: report.meeting_type || '',
    importance: report.importance || report.meeting_importance || '',
    importance_reason: report.importance_reason || '',

    summary: report.executive_brief || report.summary || '',
    architecture: report.architecture || { sections: [] },
    insights: toList(report.key_takeaways || report.insights),
    decisions: toList(report.decisions),
    key_metrics: toList(report.key_metrics || report.metrics),
    metrics: toList(report.metrics),
    risks: toList(report.risks),
    dependencies: toList(report.dependencies),
    tasks: toList(report.tasks),
    owners: toList(report.owners || report.responsibles),
    participants: Array.isArray(report.participants) ? report.participants : [],
    stats: report.stats || {}
  };
}

function toList(value) {
  if (Array.isArray(value)) {
    return value.filter((v) => !isEmptyValue(v));
  }

  if (isEmptyValue(value)) return [];
  return String(value)
    .split(/\n+/)
    .map((line) => line.trim())
    .filter(Boolean)
    .map((line) => line.replace(/^[-•]\s*/, '').trim())
    .filter((line) => !isEmptyValue(line));
 }

function parseTask(line) {
  const parts = String(line).split(/\s+—\s+|\s+-\s+/).map((p) => p.trim()).filter(Boolean);
  return {
    task: parts[0] || line,
    owner: parts[1] || '',
    dueDate: parts.slice(2).join(' — ') || ''
  };
}

function parseOwner(owner) {
    if (owner && typeof owner === 'object') {
        return {
            name: owner.name || owner.owner || owner.person || '',
            role: owner.role || owner.title || ''
        };
    }
    const parts = String(owner)
        .split(/\s+–\s+|\s+-\s+/)
        .map(p => p.trim())
        .filter(Boolean);
    return {
        name: parts[0] || owner,
        role: parts.slice(1).join(' – ')
    };
}

function initials(name) {
  return String(name || '')
    .split(/\s+/)
    .filter(Boolean)
    .slice(0, 2)
    .map((part) => part[0])
    .join('')
    .toUpperCase() || 'M';
}

function formatDate(value) {
  if (!value) return '';
  const date = new Date(value);
  if (Number.isNaN(date.getTime())) return '';
  const locale = currentLang === 'ru' ? 'ru-RU' : currentLang === 'es' ? 'es-ES' : currentLang === 'pt' ? 'pt-PT' : 'en-US';
  return new Intl.DateTimeFormat(locale, { day: 'numeric', month: 'long', year: 'numeric' }).format(date);
}

function durationLabel(seconds) {
  const s = Number(seconds);
  if (!s || s <= 0) return '';
  const minutes = Math.round(s / 60);
  return `${minutes} ${currentLang === 'ru' ? 'мин' : 'min'}`;
}

function renderTextBlock(text) {
  if (isEmptyValue(text)) return '';

  const lines = String(text).split('\n').map((l) => l.trim()).filter(Boolean);
  if (!lines.length) return '';

  const html = [];
  let listOpen = false;

  for (const line of lines) {
    const bullet = line.match(/^[-•]\s+(.*)$/);
    if (bullet) {
      if (!listOpen) {
        html.push('<ul>');
        listOpen = true;
      }
      html.push(`<li>${escapeHtml(bullet[1])}</li>`);
    } else {
      if (listOpen) {
        html.push('</ul>');
        listOpen = false;
      }
      html.push(`<p>${escapeHtml(line)}</p>`);
    }
}
  
  if (listOpen) html.push('</ul>');
  return html.join('');
}

function renderArchitecture(architecture) {

    if (!architecture) return '';
    const sections = architecture.sections || [];
    if (!sections.length) return '';
    return sections.map(section => {
        const items = section.items || [];

        if (!items.length) return '';

        return `
            <div class="architecture-section">
                <h3 class="architecture-section-title">
                    ${escapeHtml(section.title || '')}
                </h3>

                <div class="architecture-${section.layout}">

                    ${items.map(item => `
                        <div class="architecture-item">
                            <h4>${escapeHtml(item.title || '')}</h4>
                            <p>${escapeHtml(item.description || '')}</p>
                        </div>
                    `).join('')}
                </div>
            </div>
        `;
    }).join('');
}

function showToast(message) {
  const toast = $('toast');
  toast.textContent = message;
  toast.classList.remove('hidden');
  setTimeout(() => toast.classList.add('hidden'), 2600);
}

function showError(message) {
  $('loadingState').classList.add('hidden');
  $('reportPage').classList.add('hidden');
  $('deletedState').classList.add('hidden');
  $('errorTitle').textContent = 'MeetMind Report';
  $('errorText').textContent = message;
  $('errorState').classList.remove('hidden');
}

function showDeletedState() {
  $('loadingState').classList.add('hidden');
  $('reportPage').classList.add('hidden');
  $('errorState').classList.add('hidden');

  document.documentElement.lang = currentLang;
  document.title = `${t('deleted')} — MeetMind AI`;
  $('deletedTitle').textContent = t('deleted');
  $('deletedDescription').textContent = t('deletedDescription');
  $('deletedProductTitle').textContent = t('deletedProductTitle');
  $('deletedProductText').textContent = t('deletedProductText');
  $('deletedPreviewLabel').textContent = t('deletedPreviewLabel');
  $('deletedCta').textContent = t('deletedCta');
  $('deletedCtaHint').textContent = t('deletedCtaHint');
  $('deletedState').classList.remove('hidden');
}

function setLabels() {
  document.documentElement.lang = currentLang;
  $('downloadPdfBtn').textContent = t('downloadPdf');
  $('shareBtn').textContent = t('shareReport');
  $('editReportBtn').textContent = isEditMode ? t('saveChanges') : t('editReport');
  $('deleteBtn').textContent = isEditMode ? t('cancelEdit') : t('deleteReport');
  $('summaryHeading').textContent = t('executiveSummary');
  $('metricsHeading').textContent = t('keyMetrics');
  $('tasksHeading').textContent = t('tasks');
  $('detailsTitle').textContent = t('detailedReport');
  $('architectureHeading').textContent = t('architecture');
  $('ownersHeading').textContent = t('owners');
  $('transcriptHeading').textContent = t('transcript');
  $('deleteModalTitle').textContent = t('deleteTitle');
  $('deleteModalText').textContent = t('deleteText');
  $('confirmDeleteBtn').textContent = t('deleteConfirm');
  $('cancelDeleteBtn').textContent = t('cancel');
  $('transcriptToggleLabel').textContent = t('showTranscript');
  $('brandingFooter').innerHTML = `<strong>${escapeHtml(t('footerGenerated'))}</strong><span>${escapeHtml(t('footerTagline'))}</span><span>${escapeHtml(t('footerCta'))} <a href="https://t.me/meetmind_app_bot" target="_blank" rel="noopener">MeetMind AI</a></span>`;
}

function renderMeta(meeting, report) {
  const items = [];
  const date = formatDate(meeting.created_at);
  const duration = durationLabel(report.stats?.duration_seconds || meeting.duration_seconds);

  if (date) items.push(`<span class="meta-item">📅 ${escapeHtml(date)}</span>`);
  if (duration) items.push(`<span class="meta-item">🕘 ${escapeHtml(duration)}</span>`);
  items.push(`<span class="meta-item">— ${escapeHtml(t('generatedBy'))}</span>`);

  $('meetingMeta').innerHTML = items.join('');
}

function renderStats(report) {
  const stats = [];
  const duration = durationLabel(report.stats?.duration_seconds);
  const participantsCount = report.participants?.length || 0;
  const tasksCount = report.tasks.length;
  const decisionsCount = report.decisions.length;
  const risksCount = report.risks.length;

  if (duration) stats.push({ icon: '⏱', value: duration, label: t('duration') });
  if (participantsCount > 0) stats.push({ icon: '👥', value: participantsCount, label: t('participants') });
  if (tasksCount > 0) stats.push({ icon: '☑', value: tasksCount, label: t('actionItems') });
  if (decisionsCount > 0) stats.push({ icon: '⚖', value: decisionsCount, label: t('decisionCount') });
  if (risksCount > 0) stats.push({ icon: '⚠', value: risksCount, label: t('riskCount') });

  if (!stats.length) return;

  $('statsSection').innerHTML = stats.map((s) => `
    <div class="stat-item">
      <div class="stat-icon">${escapeHtml(s.icon)}</div>
      <div><div class="stat-value">${escapeHtml(s.value)}</div><div class="stat-label">${escapeHtml(s.label)}</div></div>
    </div>
  `).join('');
  $('statsSection').classList.remove('hidden');
}

function renderMetrics(report) {

  const metrics = report.key_metrics || report.metrics || [];
  if (!Array.isArray(metrics) || !metrics.length) return;
  const grid = $('metricsContent');
  let cols = metrics.length;
  if (metrics.length >= 7) {
    cols = 4;
  }

  grid.style.setProperty('--metric-cols', cols);
  grid.innerHTML = metrics.map(metric => `
    <div class="metric-card">
    <div
        class="metric-label"
        data-editable="true"
    >
        ${escapeHtml(metric.label || '')}
    </div>
    <div
        class="metric-value"
        data-editable="true"
    >
        ${escapeHtml(metric.value || '')}
    </div>
</div>
  `).join('');
  $('metricsSection').classList.remove('hidden');
}

function renderDynamicCards(report) {
  const blocks = [];
  
  if (report.insights?.length) {
    blocks.push({
      key: 'insights',
      title: t('insights'),
      items: report.insights
    });
  }

  if (report.decisions?.length) {
    blocks.push({
      key: 'decisions',
      title: t('decisions'),
      items: report.decisions
    });
  }

  if (report.risks?.length) {
    blocks.push({
      key: 'risks',
      title: t('risks'),
      items: report.risks
    });
  }

  if (!blocks.length) return;
  const grid = $('insightsDecisionsRisksGrid');
  grid.style.setProperty('--grid-cols', 1);
  const sectionsHtml = blocks.map(block => {

    const html = block.items.map(item => {
      // Старый формат (строка)
      if (typeof item === 'string') {
        return `
          <div class="report-item">
            <span class="report-dot"></span>
            <div>${escapeHtml(item)}</div>
          </div>
        `;
      }

// Новый формат (объект)

return `
  <div class="report-item" data-section="${block.key}">
    <span class="report-dot"></span>
    <div
      class="editable dynamic-item-editor"
      data-editable="true"
      data-field="${block.key}"
    >
      <strong>${escapeHtml(item.title || '')}</strong>
      ${
        item.details
          ? `<div class="item-description">${escapeHtml(item.details)}</div>`
          : ''
      }
    </div>
  </div>
`;
      
    }).join('');

    return `
    <div class="highlight-section ${block.key}">
   <h3>${escapeHtml(block.title)}</h3>
    <div class="item-list">
        ${html}
    </div>
</div>
    `;
  }).join('');
  grid.innerHTML = `
<section class="dynamic-card highlights">
    ${sectionsHtml}
</section>
`;
grid.classList.remove('hidden');
}

function renderTasksAndOwners(report) {

  console.log('owners:', report.owners);
  console.log('tasks:', report.tasks);
  
  const hasTasks = report.tasks.length > 0;
  const hasOwners = report.owners.length > 0;
  if (!hasTasks && !hasOwners) return;

  function normalizeTask(item) {
    if (typeof item === 'string') return parseTask(item);

    return {
      task: item.task || item.title || '',
      owner: item.owner || '',
      dueDate: item.due_date || item.dueDate || '',
      priority: item.business_priority || item.priority || ''
    };
  }

  function visible(value) {
    return value && value !== 'Не указано' && value !== 'Not specified';
  }

  if (hasTasks) {
    const tasks = report.tasks.map(normalizeTask).filter((task) => !isEmptyValue(task.task));

    $('tasksContent').innerHTML = `
<table class="task-table">
    <thead>
        <tr>
            <th>${escapeHtml(t('task'))}</th>
            <th>${escapeHtml(t('owner'))}</th>
            <th>${escapeHtml(t('dueDate'))}</th>
        </tr>
    </thead>
    <tbody>
        ${tasks.map(task => `
            <tr>
                <td data-editable="true">${escapeHtml(task.task)}</td>
                <td data-editable="true">${visible(task.owner) ? escapeHtml(task.owner) : ''}</td>
                <td>
                    <span class="due-badge" data-editable="true">
                        ${visible(task.dueDate) ? escapeHtml(task.dueDate) : ''}
                    </span>
                </td>
            </tr>
        `).join('')}
    </tbody>
</table>

<div class="task-cards">
${tasks.map(task => `
<div class="task-card">
    <div class="task-title"
         data-editable="true">
        ${escapeHtml(task.task)}
    </div>
    ${visible(task.owner) ? `
    <div class="task-meta task-owner">
        <strong>${escapeHtml(t('owner'))}:</strong>
        <span data-editable="true">
            ${escapeHtml(task.owner)}
        </span>
    </div>` : ''}
    ${visible(task.dueDate) ? `
    <div class="task-meta task-due">
        <strong>${escapeHtml(t('dueDate'))}:</strong>
        <span class="due-badge"
              data-editable="true">
            ${escapeHtml(task.dueDate)}
        </span>
    </div>` : ''}
</div>
`).join('')}
</div>
`;
    
    $('tasksSection').classList.remove('hidden');
  }

  if (hasOwners) {
    $('ownersContent').innerHTML = report.owners.map(parseOwner).map((owner) => `
      <div class="owner-card">
        <div class="owner-avatar">${escapeHtml(initials(owner.name))}</div>
        <div>
          <div
    class="owner-name"
    data-editable="true"
>
    ${escapeHtml(owner.name)}
</div>
         ${owner.role ? `
<div
    class="owner-role"
    data-editable="true"
>
    ${escapeHtml(owner.role)}
</div>
` : ''}
        </div>
      </div>
    `).join('');

    $('ownersSection').classList.remove('hidden');
}
}

function renderTranscript(transcript) {
  if (isEmptyValue(transcript)) return;
  $('transcriptContent').textContent = transcript;
  $('transcriptSection').classList.remove('hidden');
}

function renderReport(payload) {
  const meeting = payload.meeting;
  currentMeeting = meeting;
  const sourceLang = meeting.report_language || meeting.language || payload.language || 'en';
  currentLang = ['en', 'ru', 'es', 'pt'].includes(String(sourceLang).toLowerCase())
    ? String(sourceLang).toLowerCase()
    : 'en';
  setLabels();

  if (meeting.status === 'deleted' || meeting.deleted_at) {
    showDeletedState();
    return;
  }

  const report = normalizeReport(meeting.report || {});
  console.log(report);
  
  // The editable title is persisted inside report JSON by report-save.
  // Prefer the saved report title over the immutable/original meeting title.
  const title =
    report.meeting_title ||
    report.title ||
    meeting.meeting_title ||
    meeting.title ||
    t('meetingReport');
  
  document.title = `${title} — MeetMind AI`;
  $('meetingTitle').innerHTML = `
  <span class="editable-title" data-editable="true" data-field="meeting_title">${escapeHtml(title)}</span>
  `;

  renderMeta(meeting, report);
  renderStats(report);
  renderMetrics(report);
  
  if (!isEmptyValue(report.summary)) {
    $('summaryContent').innerHTML = renderTextBlock(report.summary);
    $('summaryContent').setAttribute('data-editable', 'true');
    $('summaryContent').setAttribute('data-field', 'summary');
    $('summarySection').classList.remove('hidden');
  }

renderDynamicCards(report);
renderTasksAndOwners(report);
renderTranscript(meeting.transcript);

  if (report.architecture?.sections?.length > 0) {
    $('architectureContent').innerHTML = renderArchitecture(report.architecture);
    $('architectureContent').setAttribute('data-editable', 'true');
    $('architectureContent').setAttribute('data-field', 'architecture');
}
  
  toggleSection(
    '#architectureSection',
    report.architecture?.sections?.length > 0
);
toggleSection(
    '#ownersSection',
    report.owners?.length > 0
);
toggleSection(
    '#transcriptSection',
    !!meeting.transcript?.trim()
);
const hasDetails =
    report.architecture?.sections?.length > 0 ||
    report.owners?.length > 0 ||
    !!meeting.transcript?.trim();
toggleSection('#detailsSection', hasDetails);

  if (meeting.branding_visible === false) $('brandingFooter').classList.add('hidden');

  $('loadingState').classList.add('hidden');
  $('reportPage').classList.remove('hidden');
  applyEditMode();
}

async function loadReportPayload() {
    const response = await fetch(
        `${REPORT_ENDPOINT}?token=${encodeURIComponent(currentToken)}`
    );

    if (!response.ok) {
        throw new Error(`HTTP ${response.status}`);
    }

    return await response.json();
}

async function loadReport() {
  const params = new URLSearchParams(window.location.search);
  currentToken = params.get('token');

  if (!currentToken) {
    showError(i18n.en.missingToken);
    return;
  }

  try {
    const payload = await loadReportPayload();

    if (!payload.success || !payload.meeting) {
      currentLang = payload.language || 'en';
      showError(t('notFound'));
      return;
    }

    renderReport(payload);
  } catch (error) {
    console.error(error);
    showError(i18n.en.notFound);
  }
}

function bindActions() {
  $('downloadPdfBtn').addEventListener(
    'click',
    showPdfBuilder
);

  $('shareBtn').addEventListener('click', async () => {
    const url = window.location.href;
    const title = currentMeeting?.title || t('meetingReport');

    if (navigator.share) {
      try {
        await navigator.share({ title, url });
        return;
      } catch (error) {
        if (error.name === 'AbortError') return;
      }
    }
    
    await navigator.clipboard.writeText(url);
    showToast(t('copied'));
  });
  
  $('editReportBtn').addEventListener('click', toggleEditMode);
  $('deleteBtn').addEventListener('click', () => {
    if (isEditMode) {
        location.reload();
        return;
    }
    $('deleteModal').classList.remove('hidden');

});
  $('cancelDeleteBtn').addEventListener('click', () => $('deleteModal').classList.add('hidden'));
  $('feedbackModalClose').addEventListener('click', hideFeedbackModal);
  $('feedbackModal').addEventListener('click', (event) => {
    if (event.target === $('feedbackModal')) hideFeedbackModal();
  });

  $('confirmDeleteBtn').addEventListener('click', async () => {
    if (!currentToken) return;

    try {
      const response = await fetch(DELETE_ENDPOINT, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ token: currentToken })
      });
      if (!response.ok) throw new Error(`HTTP ${response.status}`);
      const result = await response.json();
      if (!result.success) throw new Error(result.error || 'Delete failed');
      $('deleteModal').classList.add('hidden');
      showToast(t('deleteDone'));
      if (currentMeeting) currentMeeting.deleted_at = new Date().toISOString();
      setTimeout(showDeletedState, 350);
    } catch (error) {
      console.error(error);
      showFeedbackModal(t('deleteErrorTitle'), t('errorTryAgain'));
    }
  });

$('detailsToggle').addEventListener('click', () => {
  const content = $('detailsContent');
  const expanded = !content.classList.contains('hidden');

  content.classList.toggle('hidden', expanded);
  $('detailsToggle').setAttribute('aria-expanded', String(!expanded));
  $('detailsToggleArrow').textContent = expanded ? '▼' : '▲';
});
  
  $('transcriptToggle').addEventListener('click', () => {
    const content = $('transcriptContent');
    const expanded = !content.classList.contains('hidden');
    content.classList.toggle('hidden', expanded);
    $('transcriptToggle').setAttribute('aria-expanded', String(!expanded));
    $('transcriptToggleLabel').textContent = expanded ? t('showTranscript') : t('hideTranscript');
  });
}

bindActions();
function toggleEditMode() {

    isEditMode = !isEditMode;

    if (!isEditMode) {
        saveReport()
            .then(() => {
                console.log('Report saved successfully');
            })
            .catch(err => {
                console.error('Save error:', err);
                showFeedbackModal(t('saveErrorTitle'), t('errorTryAgain'));
            });
    }

    document.body.classList.toggle('edit-mode', isEditMode);

    setEditable('[data-editable="true"]', isEditMode);

    const btn = $('editReportBtn');
    btn.textContent = isEditMode
        ? t('saveChanges')
        : t('editReport');

    btn.classList.toggle('btn-success', isEditMode);
    btn.classList.toggle('btn-secondary', !isEditMode);

    const deleteBtn = $('deleteBtn');
    deleteBtn.textContent = isEditMode
        ? t('cancelEdit')
        : t('deleteReport');

    deleteBtn.classList.toggle('btn-warning', isEditMode);
    deleteBtn.classList.toggle('btn-danger', !isEditMode);

    console.log(btn.textContent);
    console.log('Edit mode:', isEditMode);
}

function setEditable(selector, editable) {
    document.querySelectorAll(selector).forEach(el => {
        el.contentEditable = editable;
        el.spellcheck = editable;
      el.addEventListener('keydown', (e) => {
    if (e.key === 'Enter') {
        e.preventDefault();
    }
});

      el.addEventListener('input', () => {
      cleanupEmptyDynamicItems();
});
      
        if (editable) {
            el.classList.add('editable-field');
        } else {
            el.classList.remove('editable-field');
        }
    });
}

function cleanupEmptyDynamicItems() {
    document.querySelectorAll('.report-item').forEach(item => {
        const editor = item.querySelector('.dynamic-item-editor');
        if (!editor) return;
        if (editor.innerText.trim() === '') {
            item.remove();
        }
    });
    document.querySelectorAll('.highlight-section').forEach(section => {
        if (!section.querySelector('.report-item')) {
            section.remove();
        }
    });

  const dynamicGrid = $('insightsDecisionsRisksGrid');
  if (dynamicGrid && !dynamicGrid.querySelector('.highlight-section')) {
    dynamicGrid.innerHTML = '';
    dynamicGrid.classList.add('hidden');
}

  document.querySelectorAll('.metric-card').forEach(card => {
    const label = card.querySelector('.metric-label');
    const value = card.querySelector('.metric-value');
    if (
        label &&
        value &&
        label.innerText.trim() === '' &&
        value.innerText.trim() === ''
    ) {
        card.remove();
    }
});
const metricsGrid = $('metricsContent');
if (metricsGrid && !metricsGrid.querySelector('.metric-card')) {
    $('metricsSection').classList.add('hidden');
}

  // Tasks: cards are smartphone-only; table is tablet/desktop.
  document.querySelectorAll('.task-table tbody tr').forEach(row => {
    const taskCell = row.querySelector('td:first-child');
    if (taskCell && !cleanText(taskCell.innerText)) row.remove();
  });
  document.querySelectorAll('.task-cards .task-card').forEach(card => {
    const title = card.querySelector('.task-title');
    if (title && !cleanText(title.innerText)) card.remove();
  });
  const activeTaskCount = window.matchMedia('(max-width: 767px)').matches
    ? document.querySelectorAll('.task-cards .task-card').length
    : document.querySelectorAll('.task-table tbody tr').length;
  toggleSection('#tasksSection', activeTaskCount > 0);

  // Owners: remove an owner card once both editable fields are empty.
  document.querySelectorAll('.owner-card').forEach(card => {
    const name = cleanText(card.querySelector('.owner-name')?.innerText);
    const role = cleanText(card.querySelector('.owner-role')?.innerText);
    if (!name && !role) card.remove();
  });
  toggleSection('#ownersSection', !!document.querySelector('.owner-card'));

  // Architecture: if the editable architecture body is emptied, hide the block.
  const architectureContent = $('architectureContent');
  const architectureVisible = !!architectureContent && !!cleanText(architectureContent.innerText);
  toggleSection('#architectureSection', architectureVisible);

  // Summary: no empty outer card.
  const summaryContent = $('summaryContent');
  toggleSection('#summarySection', !!summaryContent && !!cleanText(summaryContent.innerText));

  // Detailed report wrapper disappears when all detailed blocks are empty.
  const hasDetails =
    !$('#architectureSection')?.classList.contains('hidden') ||
    !$('#ownersSection')?.classList.contains('hidden') ||
    !$('#transcriptSection')?.classList.contains('hidden');
  toggleSection('#detailsSection', hasDetails);
}

function buildReportJson() {
    const baseReport = normalizeReport(currentMeeting?.report || {});

    function collectDynamicSection(sectionKey) {
        const section = document.querySelector(`.highlight-section.${sectionKey}`);
        if (!section) return [];

        return [...section.querySelectorAll('.report-item')]
            .map(item => {
                const editor = item.querySelector('.dynamic-item-editor');

                if (editor) {
                    const title = cleanText(editor.querySelector('strong')?.innerText);
                    const details = cleanText(editor.querySelector('.item-description')?.innerText);

                    if (!title && !details) return null;

                    return {
                        title,
                        details
                    };
                }

                const text = cleanText(item.innerText);
                return text ? { title: text, details: '' } : null;
            })
            .filter(Boolean);
    }

    function collectMetrics() {
        return [...document.querySelectorAll('.metric-card')]
            .map(card => ({
                label: cleanText(card.querySelector('.metric-label')?.innerText),
                value: cleanText(card.querySelector('.metric-value')?.innerText)
            }))
            .filter(metric => metric.label || metric.value);
    }

    function collectTasks() {
        // Smartphone UI edits cards; tablet/desktop edits the table.
        // Read from the representation the user actually edited.
        if (window.matchMedia('(max-width: 767px)').matches) {
            return [...document.querySelectorAll('.task-cards .task-card')]
                .map(card => ({
                    task: cleanText(card.querySelector('.task-title')?.innerText),
                    owner: cleanText(card.querySelector('.task-owner span')?.innerText),
                    due_date: cleanText(card.querySelector('.due-badge')?.innerText),
                    status: 'open'
                }))
                .filter(task => task.task);
        }

        return [...document.querySelectorAll('.task-table tbody tr')]
            .map(row => {
                const cells = row.querySelectorAll('td');

                return {
                    task: cleanText(cells[0]?.innerText),
                    owner: cleanText(cells[1]?.innerText),
                    due_date: cleanText(cells[2]?.innerText),
                    status: 'open'
                };
            })
            .filter(task => task.task);
    }

    function collectOwners() {
        return [...document.querySelectorAll('.owner-card')]
            .map(card => ({
                name: cleanText(card.querySelector('.owner-name')?.innerText),
                role: cleanText(card.querySelector('.owner-role')?.innerText)
            }))
            .filter(owner => owner.name || owner.role);
    }

    function collectArchitecture() {
        const sections = [...document.querySelectorAll('#architectureContent .architecture-section')]
            .map(section => {
                const title = cleanText(section.querySelector('.architecture-section-title')?.innerText);
                const layoutEl = [...section.querySelectorAll('div')]
                    .find(el => [...el.classList].some(cls => cls.startsWith('architecture-') && cls !== 'architecture-section'));

                const layoutClass = layoutEl
                    ? [...layoutEl.classList].find(cls => cls.startsWith('architecture-') && cls !== 'architecture-section')
                    : '';

                const layout = layoutClass ? layoutClass.replace('architecture-', '') : 'grid';

                const items = [...section.querySelectorAll('.architecture-item')]
                    .map(item => ({
                        title: cleanText(item.querySelector('h4')?.innerText),
                        description: cleanText(item.querySelector('p')?.innerText)
                    }))
                    .filter(item => item.title || item.description);

                if (!title && !items.length) return null;

                return {
                    title,
                    layout,
                    items
                };
            })
            .filter(Boolean);

        return { sections };
    }

    const title = cleanText(document.querySelector('.editable-title')?.innerText);
    const summary = cleanText($('summaryContent')?.innerText);
    const metrics = collectMetrics();

    return {
        ...baseReport,

        title,
        meeting_title: title,
        summary,
        executive_brief: summary,

        architecture: collectArchitecture(),

        key_metrics: metrics,
        metrics,

        insights: collectDynamicSection('insights'),
        decisions: collectDynamicSection('decisions'),
        risks: collectDynamicSection('risks'),

        tasks: collectTasks(),
        owners: collectOwners()
    };
}

async function saveReport() {
    const payload = {
        token: currentToken,
        report: buildReportJson()
    };

    console.log('Saving report...', payload);
    const response = await fetch(SAVE_ENDPOINT, {
        method: 'POST',
        headers: {
            'Content-Type': 'application/json'
        },
        body: JSON.stringify(payload)
    });
    if (!response.ok) {
        throw new Error(`Save failed: ${response.status}`);
    }

    const result = await response.json();
    const savedTitle = payload.report.meeting_title || payload.report.title || '';
    if (currentMeeting && savedTitle) {
        currentMeeting.title = savedTitle;
        document.title = `${savedTitle} — MeetMind AI`;
    }
    return result;
}

 function applyEditMode() {
    setEditable('[data-editable="true"]', isEditMode);
}

function toggleSection(selector, visible) {
    const section = document.querySelector(selector);
    if (!section) return;
    section.classList.toggle('hidden', !visible);
}


currentLang = detectInitialLanguage();
setLoadingLabels();
loadReport();
